services:
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aviapi_db
    networks:
      - aviapi-local


networks:
  aviapi-local: