openapi: '3.0.3'
info:
  title: FINAPI
  version: '1.0'
servers:
  - url: https://localhost:8080
paths:
  /{userID}/deposit:
    patch:
      description: Deposit money on user's account
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: 3966749e-45d4-460d-8e59-34235672f03b
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
              properties:
                amount:
                  type: number
                  format: decimal
                  minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - balance
                properties:
                  balance:
                    type: number
                    format: decimal
        '404':
          description: User Not Found
        '400':
          description: Bad Request
        '500':
          description: Internal Error

  /{userID}/transfer:
    patch:
      description: transfer money to another user
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: 3fec06e9-29cc-4ff4-9ae7-fb0e7c757b61
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - receiverID
                - amount
              properties:
                receiverID:
                  type: string
                  format: uuid
                amount:
                  type: number
                  format: decimal
                  minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transaction'
        '404':
          description: User Not Found
        '400':
          description: Bad Request
        '500':
          description: Internal Error
  /{userID}/transactions:
    get:
      description: transfer money to another user
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string
            format: uuid
          example: 3fec06e9-29cc-4ff4-9ae7-fb0e7c757b61
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transaction'
        '404':
          description: User Not Found
        '400':
          description: Bad Request
        '500':
          description: Internal Error

components:
  schemas:
    transaction:
      type: object
      required:
        - id
        - receiverID
        - senderID
        - amount
        - operation
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        receiverID:
          type: string
          format: uuid
        senderID:
          type: string
          format: uuid
        amount:
          type: number
          format: decimal
        operation:
          type: string
        createdAt:
          type: string
          format: date-time
    transactionsList:
      type: array
      items:
        $ref: '#/components/schemas/transaction'
          

